### ISSUE TITLE
Connect external repo as a dag folder

### ISSUE THREAD

**Issue by tromika** [infinitelambda/apache_airflow_on_eks#2]
First off, thanks for the heavy lifting here!

> Whenever there's any change to the Airflow Dags, the Dockerfile inside the dag folder can be built into an image, and pushed into the ECR repository.

Would it be possible to reference a git repository where our Airflow dags are located separately? As Airflow dags usually change more frequently it would be great to have less deployments. 

Thanks in advance!

**Comment by TarPeti** [comment]
Hello @tromika 
in the full airflow config template you can find configuration options for how to setup a git repository to clone it: https://github.com/apache/airflow/blob/1.10.10/airflow/config_templates/default_airflow.cfg#L877

**Comment by tromika** [comment]
Hi @TarPeti,

Ohh cool, thanks for pointing me there!
